shopping2:
  services:
    catalogue:
      uri: http://localhost:8081
      registration-id: keycloak
spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/shopping2
    username: postgres
    password: 12345678
  security:
    oauth2:
      client:
        provider:
          keycloak:
            issuer-uri: http://localhost:8082/realms/shopping2
            user-name-attribute: preferred_username
        registration:
          keycloak:
            client-id: manager-app
            client-secret: zfend08ini4FpbB8mBXr4chwp29DyZLj
            scope:
              - openid
              - view_catalogue
              - edit_catalogue
              - microprofile-jwt