shopping2:
  services:
    catalogue:
      uri: http://localhost:8081
      registration-id: keycloak
spring:
  application:
    name: manager-app
  boot:
    admin:
      client:
        url: http://localhost:8085
        instance:
          name: manager-app
          service-host-type: ip
        enabled: true
  datasource:
    url: jdbc:postgresql://localhost:5433/shopping2
    username: postgres
    password: 12345678
  security:
    oauth2:
      client:
        provider:
          keycloak:
            issuer-uri: http://192.168.0.80:8082/realms/shopping2
            user-name-attribute: preferred_username
        registration:
          keycloak:
            client-id: manager-app
            client-secret: zfend08ini4FpbB8mBXr4chwp29DyZLj
            scope:
              - openid
              - view_catalogue
              - edit_catalogue
              - microprofile-jwt
          metrics:
            provider: keycloak
            client-id: manager-app-metrics-client
            client-secret: Ox4ltZrpYUfdSy3ov4RzJTPK9AB6Tdps
            authorization-grant-type: client_credentials
            scope:
              - metrics_server
      resourceserver:
        jwt:
          issuer-uri: http://192.168.0.80:8082/realms/shopping2
management:
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true
  endpoints:
    web:
      exposure:
        include: '*'
  zipkin:
    tracing:
      endpoint: http://192.168.0.80:9411/api/v2/spans
  tracing:
    sampling:
      probability: 1.0 #normaly 30-40% genug
