server:
  port: 8083
shopping4you:
  services:
    catalogue:
      uri: lb://shopping4you-catalogue-service
    feedback:
      uri: lb://shopping4you-feedback-service
spring:
  application:
    name: customer-app
  boot:
    admin:
      client:
        enabled: false
  security:
    oauth2:
      client:
        provider:
          keycloak:
            issuer-uri: http://172.23.16.1:8082/realms/shopping2
            user-name-attribute: preferred_username
        registration:
          keycloak:
            client-id: customer-app
            client-secret: b1QAzkXaSRO4y4og0S7hZWEW9S6GP1aY
            authorization-grant-type: authorization_code
            scope:
              - openid
              - view_catalogue
          metrics:
            provider: keycloak
            client-id: customer-app-metrics-client
            client-secret: bSJJG2w9ae8Hv1dqeVhG43UgimPhwc1v
            authorization-grant-type: client_credentials
            scope:
              - metrics_server
          discovery:
            provider: keycloak
            client-id: customer-app
            client-secret: bSJJG2w9ae8Hv1dqeVhG43UgimPhwc1v
            authorization-grant-type: client_credentials
            scope:
              - discovery
      resourceserver:
        jwt:
          issuer-uri: http://172.23.16.1:8082/realms/shopping2
management:
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true
  endpoints:
    web:
      exposure:
        include: '*'
  zipkin:
    tracing:
      endpoint: http://172.23.16.1:9411/api/v2/spans
  tracing:
    sampling:
      probability: 1.0 #normaly 30-40% genug
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
